### ISSUE TITLE
Auto deploy to GitHub pages

### ISSUE THREAD

**Issue by acocheo** [certego/.github#142]
Optionally build and deploy  on GitHub Pages

For example 
```
      - name: 🚀 Deploy the website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
```

Nedded by `certego-ui`
