### ISSUE TITLE
Add workflow to publish on GH pages

### ISSUE THREAD

**Issue by acocheo** [certego/.github#184]
Workflow will:
- install npm
- run `build`
- run a job like this:
```
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
